<project name="charlesgunn project" default="dist" basedir=".">
    <description>
    charlesgunn build file
    </description>
  
  <!-- set global properties for this build -->
  <property name="src" location="src"/>
  <property name="build" location="build"/>
  <property name="dist" location="dist"/>
  <property name="apidoc" location="docs/api"/>
	<property name="weblib" location="/homes/geometer/gunn/WWW/webstart/jars-current"/>
	<property name="stdlib" location="../lib" />
  
  <target name="init">
    <mkdir dir="${build}"/>
    <mkdir dir="${dist}"/>
    <mkdir dir="${apidoc}"/>
  </target>

  <target name="core" depends="init" description="compile the source " >
    <javac  source="1.6" target="1.6" excludesfile="excludes.txt" srcdir="${src}" destdir="${build}" 
    	classpath="${stdlib}/jReality.jar:
     	${stdlib}/jReality-tutorial.jar:
        ${stdlib}/jrworkspace.jar:
    	${stdlib}/numericalMethods-22.05.06.jar:
    	${stdlib}/bsh.jar:
    	${stdlib}/mvws12.jar:
    	${stdlib}/jh.jar:
  		${stdlib}/anim.jar:
   		${stdlib}/bezierAnim.jar:
    	${stdlib}/smrj.jar:
    	${stdlib}/jtem-beans.jar:
    	${stdlib}/jogl.jar:
       	${stdlib}/projgeom.jar:
       	${stdlib}/discretegroup.jar:
      	${stdlib}/quickhull3d.jar:
   		${stdlib}/junit.jar:
    	${stdlib}/jterm.jar" debug="false">
      <compilerarg line="-source 1.5" />
    </javac>
    <copy todir="build"> <!-- copy shader progs -->
       <fileset dir="${src}">
         <exclude name="**/*.java"/>
         <exclude name="**/*.gif"/>
       </fileset>
     </copy>
  </target>

  <target name="dist" depends="core" description="generate the distribution" >
    <jar jarfile="${dist}/charlesgunn.jar" basedir="${build}">
	<manifest>
		<attribute name="Built-By" value="Charles Gunn"/>
		<attribute name="Implementation-Vendor" value="Charles Gunn"/>
		<attribute name="Implementation-Title" value="A simple key-framed animation system."/>
	</manifest>
	</jar>
	<!-- zip destfile="${dist}/charlesgunn-javadoc.zip" >
		<fileset dir="${apidoc}" />
	</zip-->
  	<!--exec dir="dist" executable="ant" >
    		<arg line=" -f /net/MathVis/signJars.xml"/>
    	</exec-->
   	<copy todir="${weblib}">
    		<fileset file="${dist}/charlesgunn.jar">
    		</fileset>
    	</copy>
 	<copy todir="${stdlib}">
  		<fileset file="${dist}/charlesgunn.jar">
  		</fileset>
  	</copy>
  </target>

  <target name="javadoc">
    <javadoc destdir="${apidoc}" author="true" version="true" use="true" windowtitle="charlesgunn java package API">
      <packageset dir="src" defaultexcludes="yes">
        <include name="charlesgunn/**" />
      </packageset>
    	<link href="http://java.sun.com/j2se/1.5/docs/api/"/>
    	<link href="http://www3.math.tu-berlin.de/jreality/api"/>
       	<link href="http://www.math.tu-berlin.de/~gunn/Documents/javaDoc/animation"/>
   		<link href="http://www.math.tu-berlin.de/jtem/beans/api/"/>
    	<link href="http://www.math.tu-berlin.de/jtem/jrworkspace/api/"/>
    	<link href="http://www.math.tu-berlin.de/jtem/jterm/api/"/>
    </javadoc>
  </target>

  <target name="clean">
    <delete dir="${build}"/>
    <delete dir="${dist}"/>
    <delete dir="${apidoc}"/>
  </target>
  
</project>
