/*******************************************************
*  Fixed.vert Fixed Function Equivalent Vertex Shader  *
*   Automatically Generated by 3Dlabs GLSL ShaderGen   *
*             http://developer.3dlabs.com              *
*******************************************************/
vec4 Ambient;
vec4 Diffuse;
vec4 Specular;


void pointLight(in int i, in vec3 normal, in vec3 eye, in vec3 ecPosition3, in gl_MaterialParameters mp)
{
   float nDotVP;       // normal . light direction
   float nDotHV;       // normal . light half vector
   float pf;           // power factor
   float attenuation;  // computed attenuation factor
   float d;            // distance from surface to light source
   vec3  VP;           // direction from surface to light position
   vec3  halfVector;   // direction of maximum highlights

   // attempt to handle directional and point lights in same code, but doesn't work
   // directional lights not filtered out by following test
   if (gl_LightSource[i].position.w != 0.0) {
   
	   // Compute vector from surface to light position
	   VP = vec3 (gl_LightSource[i].position) - ecPosition3;

	   // Compute distance between surface and light position
	   d = length(VP);

	   // Normalize the vector from surface to light position
	   VP = normalize(VP);

 	  // Compute attenuation
	   attenuation = 1.0 / (gl_LightSource[i].constantAttenuation +
	       gl_LightSource[i].linearAttenuation * d +
 	      gl_LightSource[i].quadraticAttenuation * d * d);

	   halfVector = normalize(VP - ecPosition3);

	   nDotVP = max(0.0, dot(normal, VP));
	   nDotHV = max(0.0, dot(normal, halfVector));
 	} else {
   		nDotVP = max(0.0, dot(normal, normalize(vec3 (gl_LightSource[i].position))));
   		nDotHV = max(0.0, dot(normal, vec3 (gl_LightSource[i].halfVector)));
 	}

   if (nDotVP == 0.0){
       pf = 0.0;
   }  else  {
       pf = pow(nDotHV, gl_FrontMaterial.shininess);
   }
   Ambient  += gl_LightSource[i].ambient * attenuation;
   Diffuse  += gl_LightSource[i].diffuse * nDotVP * attenuation;
   Specular += gl_LightSource[i].specular * pf * attenuation;
}

void directionalLight(in int i, in vec3 normal, in gl_MaterialParameters mp)
{
   float nDotVP;         // normal . light direction
   float nDotHV;         // normal . light half vector
   float pf;             // power factor

   nDotVP = max(0.0, dot(normal, normalize(vec3 (gl_LightSource[i].position))));
   nDotHV = max(0.0, dot(normal, vec3 (gl_LightSource[i].halfVector)));

   if (nDotVP == 0.0)
   {
       pf = 0.0;
   }
   else
   {
       pf = pow(nDotHV, mp.shininess);

   }
   Ambient  += gl_LightSource[i].ambient;
   Diffuse  += gl_LightSource[i].diffuse * nDotVP;
   Specular += gl_LightSource[i].specular * pf;
}

float ffog(in float ecDistance)
{
    return(ecDistance);
}

vec3 fnormal(void)
{
    //Compute the normal 
    vec3 normal = gl_NormalMatrix * gl_Normal;
    normal = normalize(normal);
    return normal;
}

void ftexgen(in vec3 normal, in vec4 ecPosition)
{

    gl_TexCoord[0] = gl_TextureMatrix[0]*gl_MultiTexCoord0;
    gl_TexCoord[1] = gl_TextureMatrix[1]*gl_MultiTexCoord1;
    gl_TexCoord[2] = gl_TextureMatrix[2]*gl_MultiTexCoord2;
}

vec4 dolight(in vec3 normal, in vec4 ecPosition, in gl_MaterialParameters mp)
{
    vec4 color;
    vec3 ecPosition3;

    ecPosition3 = (vec3 (ecPosition)) / ecPosition.w;

    // Clear the light intensity accumulators
    Ambient  = vec4 (0.0);
    Diffuse  = vec4 (0.0);
    Specular = vec4 (0.0);

    vec3 eye = vec3(0.0, 0.0, 0.0);
//   pointLight(0, normal, eye, ecPosition3, mp);
//   pointLight(1, normal, eye, ecPosition3, mp);
   directionalLight(0, normal, mp);
   directionalLight(1, normal, mp);

    color = //gl_FrontLightModelProduct.sceneColor +
      Ambient  * mp.ambient +
      Diffuse  * mp.diffuse+
       Specular * mp.specular;
    color = clamp( color, 0.0, 1.0 );
    return color;
}


void main (void)
{
    vec3  transformedNormal;
//    float alphaFade = 1.0;

    // Eye-coordinate position of vertex, needed in various calculations
    vec4 ecPosition = gl_ModelViewMatrix * gl_Vertex;

    // Do fixed functionality vertex transform
    gl_Position = ftransform();
    transformedNormal = fnormal();
 //   if (transformedNormal.z > 0) transformedNormal = -transformedNormal;
    gl_FrontColor = dolight(transformedNormal, ecPosition, gl_FrontMaterial);
    transformedNormal = -transformedNormal;
    gl_BackColor = dolight(transformedNormal, ecPosition, gl_BackMaterial);
    gl_FogFragCoord = ffog(ecPosition.z);
    ftexgen(transformedNormal, ecPosition);
}

