package charlesgunn.math.p5;

import charlesgunn.jreality.geometry.projective.LineUtility;
import charlesgunn.jreality.geometry.projective.PointRangeFactory;
import charlesgunn.math.clifford.MultiVectorP3;
import charlesgunn.math.clifford.ThreeSpace;
import de.jreality.geometry.QuadMeshFactory;
import de.jreality.math.Matrix;
import de.jreality.math.P3;
import de.jreality.math.Pn;
import de.jreality.math.Rn;
import de.jreality.scene.IndexedFaceSet;

// TODO: implement method which computes homogeneous coordinates of the plane in P3
// which is spanned by two intersecting plueckerLines
public class PlueckerLineGeometry {
	final public static int LINE_SPACE = 0;		// sig (3,3)
	final public static int SPHERE_SPACE = 1;	// sig (4,2)
	final public static int HYPERBOLIC = 2;		// sig (5,1)
	final public static int ELLIPTIC = 3;		// sig (6,0)

	final private static double tolerance = 10E-8;
	
	/**
	  * Calculate Pluecker coordinates for the line spanned by <i>p0</i> and <i>p1</i>.
	  * These are basically the six 2x2 minors of the 2x4 matrix formed by the two points;
	  * the fifth element has its sign reversed so the inner product has a nice symmetric form
	  * @param dst
	  * @param p0
	  * @param p1
	  * @return
	  */
	 public static double[] lineFromPoints(double[] dst, double[] p0, double[] p1)	{
		if (p0.length != 4 || p1.length != 4) {
			throw new IllegalArgumentException("Input points must be homogeneous vectors");
		}
		double[] coords;
		if (dst == null)	coords = new double[6];
		else 				coords = dst;
		coords[0] = p0[0]*p1[1] - p0[1]*p1[0];
		coords[1] = p0[0]*p1[2] - p0[2]*p1[0];
		coords[2] = p0[0]*p1[3] - p0[3]*p1[0];
		coords[3] = p0[1]*p1[2] - p0[2]*p1[1];
		coords[4] = p0[3]*p1[1] - p0[1]*p1[3];
		coords[5] = p0[2]*p1[3] - p0[3]*p1[2];
		return coords;
	}

	public static double[] lineFromPlanes(double[] dst, double[] plane0, double[] plane1)	{
		 dst = lineFromPoints(dst, plane0, plane1);
		 return dualizeLine(dst, dst);
	 }

	public static double[] intersectionPoint(double[] dst, double[] line0, double[] line1) {
		 if (dst == null) dst = new double[4];
//		 System.err.println("Line0 = "+Rn.toString(line0));
//		 System.err.println("Line1 = "+Rn.toString(line1));
		 double norm = Math.abs(innerProduct(line0, line1));
		if (norm > tolerance) {
			System.err.println("Norm exceeds tolerance: " + norm + " > " + tolerance);
			 throw new IllegalArgumentException("These two lines do not intersect");
		}
		return intersectionPointUnchecked(dst, line0, line1);
	 }
	
	public static double[] intersectionPlane(double[] dst, double[] line0, double[] line1) {
		double[] dline0 = dualizeLine(null, line0);
		double[] dline1 = dualizeLine(null, line1);
		return intersectionPoint(dst, dline0, dline1);
	 }
	
	public static double[] intersectionPointUnchecked(double[] dst, double[] line0, double[] line1) {
		 if (dst == null) dst = new double[4];
//		 System.err.println("Line0 = "+Rn.toString(line0));
//		 System.err.println("Line1 = "+Rn.toString(line1));
		 double[] mm = Rn.times(null,
				 lineToSkewMatrix(null, dualizeLine(null, line0)),
				 lineToSkewMatrix(null, line1));
		 // every column of mm should be the same point, the intersection point of the two lines
		 Matrix m = new Matrix(mm);
		 int i;
		 double norm1 = Rn.maxNorm(line0),
		 	norm2 = Rn.maxNorm(line1);
		 if (norm2 > norm1) norm1 = norm2;
		 int bestColumn = -1, biggestEntry = -1;
		 // reject columns which are the null vector (occurs when line lies in that coordinate plane)
		 // we require an entry greater than tolerance
		 double maxval = tolerance*norm1;
		 // first find a nonzero column, and its biggest entry
		 for (i = 0; i<4; ++i)	{
			 for (int j = 0; j<4; ++j) {
				 double absv = Math.abs(mm[i+4*j]);
				 if (absv > maxval) {
					 maxval = absv;
					 bestColumn = i;
					 biggestEntry = j;
				 }
			 }
			 if (bestColumn != -1) break;
			 //if (Rn.euclideanNormSquared(m.getColumn(i)) > norm*10E-16) break;
		 }
		 if (bestColumn == -1) throw new IllegalStateException("lines are same");
		 // compare the biggest entries of the remaining columns to find the best column to use
		 for (i = bestColumn+1; i<4; ++i)	{
			 double d = Math.abs(mm[i+4*biggestEntry]);
			 if (d > maxval) {maxval = d; bestColumn = i;}
		 }
		 dst[0] = mm[bestColumn+0];
		 dst[1] = mm[bestColumn+4];
		 dst[2] = mm[bestColumn+8];
		 dst[3] = mm[bestColumn+12];
		 return dst;
	 }

	/**
	 * Pluecker line coordinates can be arranged in a 4x4 skew symmetric matrix <i>M</i> such
	 * that <i>M</i> is the polarizing operator: if the original line was produced by two points,
	 * then it acts on points to give the plane spanned
	 * by the point and the line; if it was generated by two planes, then it acts on planes to give
	 * the intersection point of the line and the plane.
	 * If it's not a line, then it acts on points to give the null plane of the point, and so on.
	 * Warning: this and the following method act on points (planes) of the form (w,x,y,z), not (x,y,z,w)!
	 * @param m
	 * @param pl
	 * @return
	 */
	 public static double[] lineToSkewMatrix(double[] m, double[] pl) {
		if (m == null) m = new double[16];
		m[0] = m[5] = m[10] = m[15] = 0.0;
		m[4] = -(m[1] = pl[5]);
		m[8] = -(m[2] = pl[4]);
		m[12] = -(m[3] = pl[3]);
		m[9] = -(m[6] = pl[2]);
		m[13] = -(m[7] = -pl[1]);		// here's the strange minus sign! (p42 instead of p24 in formulas)
		m[14] = -(m[11] = pl[0]);
		return m;
		
	}

	/**
	 * Pluecker coordinates for the same line are different depending on
	 * whether the line is considered as the join of two points or the cut of two planes.
	 * This method converts between the two coordinate systems.
	 * @param dst
	 * @param src
	 * @return
	 */
	 public static double[] dualizeLine(double[] dst, double[] src) {
		if (dst == null) dst = new double[6];
		double[] tmp = null;
		if (dst == src)  tmp = new double[6];
		else tmp = dst;
		for (int i = 0; i<6; ++i) tmp[5-i] = src[i];
		if (src == dst) System.arraycopy(tmp, 0, dst, 0,  6);
		return dst;
	}
	 
	 /**
	  * reorder the pluecker line coordinates to reflect the coordinates corresponding to
	  * a given permutation of the coordinates, specified by the array <i>perm</i>.
	  * @param dst
	  * @param src
	  * @param perm
	  * @return
	  */
	 public static double[] permuteCoordinates(double[] dst, double[] src, int[] perm)	{
		 double[] P = Rn.permutationMatrix(null, perm);
		 double[] M = lineToSkewMatrix(null, src);
		 double[] MM = Rn.conjugateByMatrix(null, M, P);
		 if (dst == null) dst = new double[src.length];
		 dst[0] = MM[11];
		 dst[1] = -MM[7];
		 dst[2] = MM[6];
		 dst[3] = MM[3];
		 dst[4] = MM[2];
		 dst[5] = MM[1];
		 return dst;
	 }

	public static double innerProduct(double[] l0, double[] l1) {
		double sum = 0;
		for (int i = 0; i<6; ++i)	{
			sum += l0[i] * l1[5-i];
		}
		return sum;
	}
	/*
	 * The following methods use Pluecker line coordinates to calculate quantities in P3.
	 * Perhaps they belong in another, derived package
	 */
	/**
	 * Project the point <i>p</i> onto the line spanned by <i>v0</i> and <i>v1</i> perpendicularly.
	 * @param dst
	 * @param p
	 * @param v0
	 * @param v1
	 * @param metric	a metric from P3! (not P5)
	 * @return
	 */
	public static double[] projectPointOntoLine(double[] dst, double[] p, double[] v0, double[] v1, int metric) {
		if (dst == null) dst = new double[4];
		if (metric == Pn.EUCLIDEAN)	{
			double[] dv = Rn.subtract(null, v1, v0);
			double[] dp = Rn.subtract(null, p, v0);
			double[] proj = Rn.projectOnto(null, dp, dv);
			Rn.add(dst, v0, proj);
			return dst;
		}
		double[] polar0 = Pn.polarizePoint(null, v0, metric);
		double[] polar1 = Pn.polarizePoint(dst, v1, metric);
		double[] line = lineFromPlanes(null, polar0, polar1);
		double[] plane = lineJoinPoint(null, line, p);
		P3.lineIntersectPlane(dst, v0, v1, plane);
		return dst;
		}

	public static double[] projectPointOntoLine(double[] dst, double[] p, double[] line, int metric) {
		if (dst == null) dst = new double[4];
		double[] polarLine = polarize(null, line, metric);
		double[] plane = lineJoinPoint(null, polarLine, p);
		lineIntersectPlane(dst, line, plane);
		return dst;
		}

	/**
	 * 
	 * @param point
	 * @param plueckerLine
	 * @param plane
	 * @return
	 * @see {@link de.jreality.math.P3#lineIntersectPlane(double[], double[], double[], double[])}
	 */
	public static double[] lineIntersectPlane(double[] point,double[] plueckerLine, double[] plane )	{
		return Rn.matrixTimesVector(point, 
				lineToSkewMatrix(null, dualizeLine(null, plueckerLine)), 
				plane); 
	 }

	/**
	 * 
	 * @param dst
	 * @param plueckerLine
	 * @param point
	 * @return
	 * @see {@link de.jreality.math.P3#lineJoinPoint(double[], double[], double[], double[])}
	 */
	public static double[] lineJoinPoint(double[] dst, double[] plueckerLine, double[] point)	{
		return Rn.matrixTimesVector(dst, lineToSkewMatrix(null, plueckerLine), point); 
	}
	
	public static double[] normalize(double[] dst, double[] src)	{
		if (dst == null) dst = new double[6];
		double x = src[2]*src[2] + src[4]*src[4] + src[5]*src[5];
		if (x == 0.0)	{
			System.arraycopy(src, 0, dst, 0, 6);
			return dst;
		}
		x = 1.0/Math.sqrt(x);
		Rn.times(dst, x, src);
		return dst;
	}
	
	private static double[] directionVector(double[] dst, double[] line)	{
		return new double[]{line[2], -line[4], line[5]};
	}
		
	public static double cosineBetweenLines(double[] line1, double[] line2) {
		double[] dv1 = directionVector(null, line1);
		double[] dv2 = directionVector(null, line2);
		double d11 = Rn.innerProduct(dv1, dv1);
		double d12 = Rn.innerProduct(dv1, dv2);
		double d22 = Rn.innerProduct(dv2, dv2);
		return d12/Math.sqrt(d11*d22);
	}
	
	public boolean isInfinite(double[] line)	{
		double[] dv = directionVector(null, line);
		double ll = Rn.innerProduct(dv, dv);
		return ll == 0.0;
	}
	
	public static double distanceBetweenLines(double[] l1, double[] l2)	{
		if (LieSphereGeometry.isInfinity(l1) || LieSphereGeometry.isInfinity(l2))	{
			throw new IllegalArgumentException("Invalid argument: line at infinity");
		}
		double[] line1 = normalize(null, l1);
		double[] line2 = normalize(null, l2);
		double k12, c12;
		k12 = innerProduct(line1, line2);
		c12 = cosineBetweenLines(line1, line2);
//		System.err.println(" dot = "+k12);
//		System.err.println(" cos = "+c12);
//		System.err.println(" rad = "+k12/(Math.sqrt(1-c12*c12)));
		return Math.abs(k12/(Math.sqrt(1-c12*c12)));
	}

	static int[][] plueckerIndices = {{0,1},{0,2},{0,3},{1,2},{3,1},{2,3}};
	/**
	 * TODO: create two versions of this, one for collineations, one for correlations
	 * @param dst
	 * @param p3m
	 * @return
	 */
	public static double[] inducedP5ProjFromP3Proj(double[] dst, double[] p3m)	{
		if (dst == null) dst = new double[36];
		for (int i = 0; i<6; ++i)	{
			int ii = plueckerIndices[i][0];
			int jj = plueckerIndices[i][1];
			for (int j = 0; j<6; ++j)	{
				int kk = plueckerIndices[j][0];
				int mm = plueckerIndices[j][1];
				int ind = (i)*6+j;
				dst[ind] = p3m[ii*4+kk]*p3m[jj*4+mm] - p3m[ii*4+mm]*p3m[jj*4+kk];
			}
		}
		return dst;
	}
	
	public static double[] conjugateWithRespectToComplex(double[] dst, double[] complex, double[] line)	{
		if (dst == null) dst = new double[6];
		double[] p5m = PlueckerLineGeometry.inducedP5ProjFromP3Proj(null, lineToSkewMatrix(null, complex));
		Rn.matrixTimesVector(dst, p5m, line);
		// the projectivity above is actually a correlation so we have to flip the result
		dualizeLine(dst, dst);
		return dst;
	}

	public static double[] nullPlane(double[] dst, double[] complex, double[] point)	{
		double[] skew = lineToSkewMatrix(null, complex);
		return Rn.matrixTimesVector(dst, skew, point);
	}
	
	public static double[] nullPoint(double[] dst, double[] complex, double[] plane)	{
		double[] skew = lineToSkewMatrix(null, dualizeLine(null, complex));
		return Rn.matrixTimesVector(dst, skew, plane);
	}
	
	public static boolean isValidLine(double[] ds) {
		double euc2 = Rn.euclideanNormSquared(ds);
		if (euc2 < 10E-16) return false;
		double pl = innerProduct(ds, ds);
		if (pl > 10E-8) return false;
		return true;
	}
	
	// TODO get rid of these hard-wired indices. They assume the 3rd coordinate is 
	// the homogeneous one (2,4, 5) correspond to bivector indices 03, 13, and 23
	public static double[] polarize(double[] dst, double[] src, int metric)	{
		dst = dualizeLine(dst, src);
		dst[2] *= metric; dst[4] *= metric;  dst[5] *= metric;
		return dst;
	}

	public static double getTolerance() {
		return tolerance;
	}
	
	public static double[] closestPoint(double[] ret, double[] point, double[] line, int metric)	{
		
		return point;
	}
	
	/**
	 * This may only make sense in the euclidean case ... for which every regulus has a well-defined
	 * "narrowest" cross-section or waist, characterized by its plane and its center. The pole of each is 
	 * an ideal element.  We find it by first finding the three euclidean common normals of the
	 * 3 generators taken 2 at a time.  We calculate their 6 intersection points with the generators,
	 * and take the midpoints of the 3 resulting segments.  These three points lie on the regulus and 
	 * determine its waist plane.  The center of the waist is the center of the circle that they lie on. 
	 * There must be an easier way to calculate this
	 * @param ret
	 * @param generators
	 * @param metric
	 * @return
	 */
	public static double[][] getWaistPlaneForRegulus(double[][] ret, double[][] generators, int metric) {
		return ret;
	}
	
//	public static double[] permuteCoordinates(double[] dst, double[] src, int[] perm) {
//		double[] permM = Rn.permutationMatrix(null, perm);
//		double[] induced = PlueckerLineGeometry.inducedP5ProjFromP3Proj(null, permM);
//		return Rn.matrixTimesVector(dst, induced, src);
//	}
	// calculate the set of lines defining the Clifford torus centered on
	// axis of radius angle.
	public static double[][] cliffordTorus(double[][] dst, double[] axis, double angle, int n)	{
		double[][] cliffordParallels = dst == null ?  new double[n][] : dst;
		double[] polarAxis = PlueckerLineGeometry.polarize(null, axis, Pn.ELLIPTIC);
		double[][] pointOnA = LineUtility.twoPointsOnLine(null, axis);
		double[][] pointOnPA = LineUtility.twoPointsOnLine(null, polarAxis);
		// make sure second point is orthogonal to the first
		pointOnPA[1] = PlueckerLineGeometry.lineIntersectPlane(null, 
				polarAxis, 
				Pn.polarize(null, pointOnPA[0], Pn.ELLIPTIC));
		for (int i = 0; i<n; ++i)	{
			double pangle = 2*Math.PI*(i/(n-1.0));
			double[] P = Rn.add(null, 
					Rn.times(null, Math.cos(pangle), pointOnPA[0]), 
					Rn.times(null, Math.sin(pangle), pointOnPA[1]));
			P = Pn.normalize(null, P, Pn.ELLIPTIC);
			double[] Q = Rn.add(null, 
					Rn.times(null, Math.cos(angle), pointOnA[0]), 
					Rn.times(null, Math.sin(angle), P));
			double[] iso = P3.makeScrewMotionMatrix(null, P, Q, angle, Pn.ELLIPTIC);
			double[] isoP5 = PlueckerLineGeometry.inducedP5ProjFromP3Proj(null, iso);
			cliffordParallels[i] = Rn.matrixTimesVector(null, isoP5, axis);
		}
		return cliffordParallels;
	}
	
	public static IndexedFaceSet equidistantSurface(double[] axis, double angle, int n)	{
		double[] polarAxis = PlueckerLineGeometry.polarize(null, axis, Pn.ELLIPTIC);
		double[][] pointOnA = LineUtility.twoPointsOnLine(null, axis);
		double[][] pointOnPA = LineUtility.twoPointsOnLine(null, polarAxis);
		// make sure second point is orthogonal to the first
		pointOnPA[1] = PlueckerLineGeometry.lineIntersectPlane(null, 
				polarAxis, 
				Pn.polarize(null, pointOnPA[0], Pn.ELLIPTIC));
		Pn.normalize(pointOnA, pointOnA, Pn.ELLIPTIC);
		Pn.normalize(pointOnPA, pointOnPA, Pn.ELLIPTIC);
		double[] Q = Rn.add(null, 
				Rn.times(null, Math.cos(angle), pointOnA[0]), 
				Rn.times(null, Math.sin(angle), pointOnPA[0]));
		double[] iso = P3.makeScrewMotionMatrix(null, pointOnA[0]	, Q, angle, Pn.ELLIPTIC);
		double[] isoP5 = PlueckerLineGeometry.inducedP5ProjFromP3Proj(null, iso);
		double[] cliffordParallel = Rn.matrixTimesVector(null, isoP5, axis);
	
		PointRangeFactory prf = new PointRangeFactory();
		prf.setPluckerLine(cliffordParallel);
		prf.setNumberOfSamples(6 );
		prf.setFiniteSphere(false);
		prf.update();
		double[][] tmp = prf.getSamples();
		double[][] pointsOnCP = new double[tmp.length+1][];
		for (int i = 0; i<tmp.length; ++i)	{
			pointsOnCP[i] = tmp[i];
		}
		pointsOnCP[tmp.length] = tmp[0];
		
		double[][][] tubePoints = new double[n][][];
		ThreeSpace ts = new ThreeSpace(Pn.ELLIPTIC);
		double[] axisNewCoords = dualizeLine(null, permuteCoordinates(null, axis, new int[]{1,2,3,0}));
		MultiVectorP3 axisMV = MultiVectorP3.line(axisNewCoords);
		for (int i = 0; i<n; ++i)	{
			double pangle = (2*Math.PI*i)/(n-1);
			MultiVectorP3 rotor = ts.exp(null, axisMV, pangle/2);
//			MultiVectorP3 clifParallel2MV = ts.sandwichProduct(rotor, clifParallelMV);
			double[] M = P3.makeRotationMatrix(null, pointOnA[0], pointOnA[1], pangle, Pn.ELLIPTIC);
			double[] M2 = ts.matrixForRotor(rotor);
//			System.err.println("matrix LA= \n"+Rn.matrixToString(M, "%6.2f"));
//			System.err.println("matrix CA= \n"+Rn.matrixToString(M2, "%6.2f"));
			tubePoints[i] = Rn.matrixTimesVector(null, M2, pointsOnCP);
		}
//		System.err.println("quad mesh = \n"+Rn.toString(tubePoints));
		QuadMeshFactory qmf = new QuadMeshFactory();
		qmf.setMetric(Pn.ELLIPTIC);
		qmf.setULineCount(tubePoints[0].length);
		qmf.setVLineCount(tubePoints.length);
		qmf.setClosedInUDirection(false);		
		qmf.setClosedInVDirection(false);
		qmf.setVertexCoordinates(tubePoints);
		qmf.setGenerateEdgesFromFaces(true);
		qmf.setGenerateFaceNormals(true);
		qmf.setGenerateVertexNormals(true);
		qmf.update();
		IndexedFaceSet qms = qmf.getIndexedFaceSet();
		return qms;
	}
}
